"use client";

import { tokens, Field, inputStyle, Pill } from "./shared";
import type { ProcedureFormData } from "@/lib/pricing-rules/types";

function ReadOnly({ isDark, value }: { isDark: boolean; value: string }) {
  const t = tokens(isDark);
  return <div style={{ ...inputStyle(t, { readOnly: true }) }}>{value?.trim() ? value : "Not Available"}</div>;
}

/**
 * §4/§5 Product Information strip — shown only for attribute-based
 * pricing. Every field here is system-generated by the Salesforce
 * auto-discovery cascade and rendered read-only ("Not Available" rather
 * than a blank input when not yet resolved) EXCEPT Effective From/To and
 * Procedure Status, which remain user-editable. A single responsive grid
 * (instead of several fixed-width rows) so the card fills the page's
 * wider layout on large screens and reflows cleanly on narrow ones.
 */
export default function ProductInfoStrip({
  isDark,
  form,
  onChange,
}: {
  isDark: boolean;
  form: ProcedureFormData;
  onChange: (field: keyof ProcedureFormData, value: string) => void;
}) {
  const t = tokens(isDark);
  return (
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 12 }}>
      <Field label="Product ID" isDark={isDark}><ReadOnly isDark={isDark} value={form.productId} /></Field>
      <Field label="Product Code" isDark={isDark}><ReadOnly isDark={isDark} value={form.productCode} /></Field>
      <Field label="Product Status" isDark={isDark}>
        {form.productStatus ? (
          <Pill label={form.productStatus} color={form.productStatus === "Active" ? "#22C55E" : t.dim} isDark={isDark} />
        ) : (
          <ReadOnly isDark={isDark} value="" />
        )}
      </Field>
      <Field label="Currency" isDark={isDark}><ReadOnly isDark={isDark} value={form.currency} /></Field>

      <Field label="Selling Model" isDark={isDark}><ReadOnly isDark={isDark} value={form.sellingModel} /></Field>
      <Field label="Selling Model ID" isDark={isDark}><ReadOnly isDark={isDark} value={form.sellingModelId} /></Field>
      <Field label="Effective From" isDark={isDark} required>
        <input type="date" value={form.effectiveFrom} onChange={e => onChange("effectiveFrom", e.target.value)} style={inputStyle(t)} />
      </Field>
      <Field label="Effective To" isDark={isDark}>
        <input type="date" value={form.effectiveTo} onChange={e => onChange("effectiveTo", e.target.value)} style={inputStyle(t)} />
      </Field>

      <Field label="Procedure Status" isDark={isDark}>
        <select value={form.procedureStatus} onChange={e => onChange("procedureStatus", e.target.value)} style={inputStyle(t)}>
          <option value="Draft">Draft</option>
          <option value="Active">Active</option>
        </select>
      </Field>
    </div>
  );
}
