import type { BrandingConfig, MergeFieldValues } from "@/lib/contracts/types";
import { substituteMergeFields } from "@/lib/contracts/documents/mergeFields";

export const DEFAULT_BRANDING: BrandingConfig = {
  companyName: "Your Company",
  logoUrl: null,
  primaryColor: "#0047AB",
  font: "Helvetica",
  footerText: "Confidential — generated by OmniCloud RCA Accelerator.",
  termsText: "This document is subject to the terms and conditions referenced herein.",
  signatureBlockText: "By signing below, each party agrees to be bound by the terms of this Agreement.",

  logoWidth: 120,
  logoHeight: 40,
  logoMaintainAspectRatio: true,
  logoPosition: "left",
  headerMargin: 20,
  footerMargin: 20,

  fontFamily: "Helvetica, Arial, sans-serif",
  fontSize: 11,
  headingFont: "Helvetica, Arial, sans-serif",
  paragraphFont: "Helvetica, Arial, sans-serif",
  lineHeight: 1.5,
  letterSpacing: 0,
  textColor: "#1A1A1A",
  pageBackground: "#FFFFFF",

  pageSize: "A4",
  orientation: "portrait",
  pageMargins: { top: 48, right: 48, bottom: 48, left: 48 },
  headerHeight: 60,
  footerHeight: 50,

  footerElements: ["confidential", "pageNumber"],

  signatureBlocks: [
    { id: "customer-signature", type: "customerSignature", label: "Customer Signature", required: true, order: 1, width: 260, height: 80, alignment: "left", border: true },
    { id: "company-signature", type: "companySignature", label: "Company Signature", required: true, order: 2, width: 260, height: 80, alignment: "right", border: true },
  ],
};

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/** Strips the handful of constructs that would let a custom template body execute script in the preview — narrow, not a full sanitizer, since only authenticated org users author these bodies. */
function sanitizeBasic(html: string): string {
  return html.replace(/<script[\s\S]*?<\/script>/gi, "").replace(/ on[a-z]+="[^"]*"/gi, "").replace(/ on[a-z]+='[^']*'/gi, "");
}

const FOOTER_ELEMENT_LABELS: Record<BrandingConfig["footerElements"][number], (b: BrandingConfig) => string> = {
  confidential: () => "Confidential",
  companyAddress: b => b.companyName,
  pageNumber: () => "Page 1 of 1",
  generatedDate: () => `Generated ${new Date().toLocaleDateString()}`,
  version: () => "v1",
  copyright: b => `© ${new Date().getFullYear()} ${b.companyName}`,
};

/** Renders the footer's enabled elements, in configured order, for both the HTML preview and (via the same list) the Print/PDF previews. */
export function renderFooterElements(branding: BrandingConfig): string[] {
  return branding.footerElements.map(key => FOOTER_ELEMENT_LABELS[key](branding));
}

const JUSTIFY_FOR_POSITION: Record<BrandingConfig["logoPosition"], string> = { left: "flex-start", center: "center", right: "flex-end" };

/**
 * One shared branding-resolution function used identically by both the HTML
 * preview and the PDF generator (§4.3) — so preview and generated PDF can
 * never drift on branding. This is the HTML side; lib/contracts/documents/pdf.ts
 * applies the same BrandingConfig to the PDF renderer's own primitives.
 */
export function renderBrandedHtml(bodyHtml: string, branding: BrandingConfig, values: MergeFieldValues): string {
  const merged = sanitizeBasic(substituteMergeFields(bodyHtml, values));
  const m = branding.pageMargins;
  return `<div style="font-family: ${branding.fontFamily}; font-size: ${branding.fontSize}pt; line-height: ${branding.lineHeight}; letter-spacing: ${branding.letterSpacing}px; color: ${branding.textColor}; background: ${branding.pageBackground}; max-width: 720px; margin: 0 auto; padding: ${m.top}px ${m.right}px ${m.bottom}px ${m.left}px;">
    <div style="display:flex; align-items:center; justify-content:${JUSTIFY_FOR_POSITION[branding.logoPosition]}; gap:12px; border-bottom: 3px solid ${branding.primaryColor}; padding-bottom: ${branding.headerMargin}px; margin-bottom: 20px; min-height: ${branding.headerHeight}px;">
      ${branding.logoUrl ? `<img src="${branding.logoUrl}" alt="" style="width:${branding.logoWidth}px; height:${branding.logoMaintainAspectRatio ? "auto" : `${branding.logoHeight}px`}; object-fit: contain;" />` : ""}
      <div style="font-size: 18px; font-weight: 700; color: ${branding.primaryColor}; font-family: ${branding.headingFont};">${escapeHtml(branding.companyName)}</div>
    </div>
    <div style="font-family: ${branding.paragraphFont};">${merged}</div>
    <div style="margin-top: 24px; padding-top: 12px; border-top: 1px solid #ddd; font-size: 12px; color: #555;">
      <p>${escapeHtml(branding.termsText)}</p>
      <p>${escapeHtml(branding.signatureBlockText)}</p>
    </div>
    <div style="margin-top: ${branding.footerMargin}px; min-height: ${branding.footerHeight}px; display:flex; flex-wrap: wrap; gap: 16px; font-size: 10.5px; color: #999;">
      ${renderFooterElements(branding).map(escapeHtml).map(el => `<span>${el}</span>`).join("")}
    </div>
  </div>`;
}
